/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.touristDashboard;

import java.awt.Color;

/**
 *
 * @author duktartamang
 */
public class StaysDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form Stays
     */
    public StaysDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kathmandu = new javax.swing.JLabel();
        pokhara = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        KathmanduIcon = new javax.swing.JLabel();
        pokharaIcon = new javax.swing.JLabel();
        chitwanIcon = new javax.swing.JLabel();
        location = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kathmanduprice = new javax.swing.JButton();
        details = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pokharaprice = new javax.swing.JButton();
        details1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        details2 = new javax.swing.JButton();
        chitwanPrice = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Book = new javax.swing.JButton();
        Book1 = new javax.swing.JButton();
        Book2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(2560,1600);
        getContentPane().setLayout(null);
        setBackground(Color.black);

        jLabel1.setFont(new java.awt.Font("Optima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("GHU-MANTEY");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 161, 64);

        jLabel2.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Available Hotels");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 50, 139, 35);

        kathmandu.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        kathmandu.setText("Kathmandu Guest House");
        getContentPane().add(kathmandu);
        kathmandu.setBounds(410, 120, 200, 33);

        pokhara.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pokhara.setText("Pokahra Guest House");
        getContentPane().add(pokhara);
        pokhara.setBounds(430, 350, 181, 33);

        Logo.setText("Logo");
        getContentPane().add(Logo);
        Logo.setBounds(210, 30, 31, 16);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 234, 0, 0);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(52, 240, 0, 0);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("chitwan Guest House");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(410, 620, 159, 17);

        KathmanduIcon.setText("KathmanduIcon");
        getContentPane().add(KathmanduIcon);
        KathmanduIcon.setBounds(820, 160, 98, 59);

        pokharaIcon.setText("PokharaIcon");
        getContentPane().add(pokharaIcon);
        pokharaIcon.setBounds(850, 420, 77, 16);

        chitwanIcon.setText("ChitwanIcon");
        getContentPane().add(chitwanIcon);
        chitwanIcon.setBounds(850, 660, 78, 16);

        location.setText("Location");
        getContentPane().add(location);
        location.setBounds(340, 180, 54, 16);

        jLabel4.setText("Kathmandu/thamel/23rdstreet");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 180, 193, 16);

        jLabel8.setText("Contacts");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 230, 56, 16);

        jLabel9.setText("9856472648");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 230, 80, 16);

        kathmanduprice.setText("Price");
        kathmanduprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kathmandupriceActionPerformed(evt);
            }
        });
        getContentPane().add(kathmanduprice);
        kathmanduprice.setBounds(330, 290, 75, 29);

        details.setText("Details");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details);
        details.setBounds(490, 290, 88, 29);

        jLabel3.setText("Location");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 420, 54, 16);

        jLabel10.setText("Pokhara/chinaTown/12thStreet");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 420, 197, 16);

        jLabel11.setText("Contacts");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 480, 56, 16);

        jLabel12.setText("9864527453");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(500, 480, 80, 16);

        pokharaprice.setText("Price");
        pokharaprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokharapriceActionPerformed(evt);
            }
        });
        getContentPane().add(pokharaprice);
        pokharaprice.setBounds(340, 550, 75, 29);

        details1.setText("Details");
        details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details1ActionPerformed(evt);
            }
        });
        getContentPane().add(details1);
        details1.setBounds(490, 550, 88, 29);

        jLabel13.setText("Location");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 660, 54, 16);

        jLabel14.setText("Chitwan/Tharutole/2ndStreet");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(520, 660, 185, 16);

        jLabel15.setText("Contacts");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(370, 720, 56, 16);

        jLabel16.setText("9746372564");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(530, 720, 80, 16);

        details2.setText("Details");
        details2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                details2ActionPerformed(evt);
            }
        });
        getContentPane().add(details2);
        details2.setBounds(520, 770, 88, 29);

        chitwanPrice.setText("Price");
        getContentPane().add(chitwanPrice);
        chitwanPrice.setBounds(360, 770, 75, 29);

        jLabel17.setText("Name");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(20, 420, 36, 16);

        jLabel18.setText("Pokhara Guest House");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(140, 420, 150, 16);

        jLabel19.setText("Gmail");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 480, 53, 16);

        jLabel20.setText("PokharaguestH@gmail.com");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(140, 480, 172, 16);

        jLabel21.setText("Name");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(10, 680, 36, 16);

        jLabel22.setText("Chitwan Guest House");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(150, 660, 150, 16);

        jLabel23.setText("Gmail");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 730, 36, 16);

        jLabel24.setText("ChitwanG@gmail.com");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(150, 720, 150, 16);

        jLabel25.setText("Name");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 180, 40, 20);

        jLabel26.setText("Kathmandu Guest House");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(140, 180, 180, 20);

        jLabel27.setText("Gmail");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 230, 36, 16);

        jLabel28.setText("Kathmandu");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(160, 230, 90, 16);

        Book.setText("Book");
        Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookActionPerformed(evt);
            }
        });
        getContentPane().add(Book);
        Book.setBounds(1160, 290, 75, 29);

        Book1.setText("Book");
        Book1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book1ActionPerformed(evt);
            }
        });
        getContentPane().add(Book1);
        Book1.setBounds(1160, 550, 70, 30);

        Book2.setText("Book");
        getContentPane().add(Book2);
        Book2.setBounds(1160, 760, 70, 30);

    }// </editor-fold>                        

    private void kathmandupriceActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void pokharapriceActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void details1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void details2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BookActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void Book1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    /**
     * @param args the command line arguments
     */
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new StaysDashBoard().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Book;
    private javax.swing.JButton Book1;
    private javax.swing.JButton Book2;
    private javax.swing.JLabel KathmanduIcon;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel chitwanIcon;
    private javax.swing.JButton chitwanPrice;
    private javax.swing.JButton details;
    private javax.swing.JButton details1;
    private javax.swing.JButton details2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel kathmandu;
    private javax.swing.JButton kathmanduprice;
    private javax.swing.JLabel location;
    private javax.swing.JLabel pokhara;
    private javax.swing.JLabel pokharaIcon;
    private javax.swing.JButton pokharaprice;
    // End of variables declaration                   
}
