package view.touristDashboard;

import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author duktartamang
 */
public class StaysDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form StaysDashBoard
     */
    public StaysDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Detailsbtn = new javax.swing.JButton();
        pricebtn = new javax.swing.JButton();
        Details2btn = new javax.swing.JButton();
        price2btn = new javax.swing.JButton();
        Icon = new javax.swing.JLabel();

        setSize(2560,1600);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        Detailsbtn.setText("Details");
        getContentPane().add(Detailsbtn);
        Detailsbtn.setBounds(20, 620, 75, 29);

        pricebtn.setText("Price");
        pricebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricebtnActionPerformed(evt);
            }
        });
        getContentPane().add(pricebtn);
        pricebtn.setBounds(120, 620, 75, 29);

        Details2btn.setText("Details");
        getContentPane().add(Details2btn);
        Details2btn.setBounds(720,620, 75, 29);

        price2btn.setText("Price");
        getContentPane().add(price2btn);
        price2btn.setBounds(820,620, 75, 29);

        Icon.setIcon(new ImageIcon("Photos/Hotel up in the MOuntain-2.png"));
        getContentPane().add(Icon);
        Icon.setBounds(-10,0,1600,1050);

      
    }// </editor-fold>                        

    private void pricebtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

   
    // public static void main(String args[]) {
    //     /* Set the Nimbus look and feel */
    //     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //      * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //      */
    //     try {
    //         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //             if ("Nimbus".equals(info.getName())) {
    //                 javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                 break;
    //             }
    //         }
    //     } catch (ClassNotFoundException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (InstantiationException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (IllegalAccessException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //         java.util.logging.Logger.getLogger(StaysDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //     }
    //     //</editor-fold>

    //     /* Create and display the form */
    //     java.awt.EventQueue.invokeLater(new Runnable() {
    //         public void run() {
    //             new StaysDashBoard().setVisible(true);
    //         }
    //     });
    // }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Details2btn;
    private javax.swing.JButton Detailsbtn;
    private javax.swing.JLabel Icon;
    private javax.swing.JButton price2btn;
    private javax.swing.JButton pricebtn;
    // End of variables declaration                   
}
